# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-09 12:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='invoice/%Y/%m/%d')),
                ('status', models.CharField(blank=True, choices=[('ST', 'STARTED'), ('IP', 'IN PROGRESS'), ('CD', 'COMPLETED'), ('FD', 'FAILED')], max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('validation_results', models.TextField(blank=True, null=True)),
                ('progress', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(db_index=True, unique=True)),
                ('date', models.DateField(default=datetime.datetime(2020, 2, 9, 11, 59, 59, 695337, tzinfo=utc))),
                ('due_date', models.DateField(default=datetime.datetime(2020, 2, 9, 11, 59, 59, 695372, tzinfo=utc))),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('unit_amount', models.IntegerField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_customer', to='csvfiletask.Customer', verbose_name='Customer')),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_file', to='csvfiletask.File', verbose_name='File')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
    ]
