# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-09 12:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('csvfiletask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 9, 12, 0, 10, 637450, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2020, 2, 9, 12, 0, 10, 637504, tzinfo=utc)),
        ),
    ]
