# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-09 21:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('csvfiletask', '0002_auto_20200209_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 9, 21, 33, 21, 502573, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2020, 2, 9, 21, 33, 21, 502609, tzinfo=utc)),
        ),
    ]
