# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-11 09:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('csvfiletask', '0004_auto_20200210_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 11, 9, 16, 29, 255032, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2020, 2, 11, 9, 16, 29, 255064, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
