# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-12-27 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('project', 'PROJECT'), ('about me', 'ABOUT ME')], default='project', max_length=20),
        ),
    ]
