# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-22 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequestDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('content_type', models.TextField()),
                ('query_string', models.CharField(max_length=100)),
                ('browser_detail', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ClientRequestDetail',
                'verbose_name_plural': 'ClientRequestDetails',
                'ordering': ['-date_added'],
            },
        ),
    ]
